Update patch set 11
Patch Set 11:

> Patch Set 11:
> 
> > Patch Set 11:
> > 
> > > Patch Set 11:
> > > 
> > > I believe this caused the deps roller to be stuck:
> > > 
> > > https://chromium-review.googlesource.com/c/609307
> > > 
> > > ../../third_party/pdfium/testing/libfuzzer/pdf_codec_rle_fuzzer.cc:15: error: undefined reference to 'CCodec_BasicModule::RunLengthEncode(unsigned char const*, unsigned int, unsigned char**, unsigned int*)'
> > > ../../third_party/pdfium/third_party/base/allocator/partition_allocator/partition_alloc.h:463: error: undefined reference to 'pdfium::base::PartitionAllocHooks::free_hook_'
> > > ../../third_party/pdfium/third_party/base/allocator/partition_allocator/partition_alloc.h:745: error: undefined reference to 'pdfium::base::PartitionFreeSlowPath(pdfium::base::PartitionPage*)'
> > 
> > Unittests and embeddertests fail to link.
> 
> Nicolas, what gn args are you using? This should only happen when you do a component build. I can whip up a temporary fix so the tests keep working but in the long run they will need some proper refactoring to work with a shared library build of pdfium.

Felix, sorry I meant when trying to compile on Chrome. If a CL breaks compiling on Chrome then that won't work. In Chrome people we can use is_component_build=true and it should not break linkage of PDFium targets.

Patch-set: 11