Update patch set 7
Patch Set 7:

> Patch Set 7:
> 
> > Patch Set 6:
> > 
> > > Patch Set 6:
> > > 
> > > Hurm, that compiles successfully. I don't get the error the bots are getting. Still digging around.
> > 
> > I'm able to reproduce. Try these gn args:
> > use_goma = true  # Googlers only.
> > is_debug = true # Enable debugging features.
> > 
> > pdf_use_skia = false # Set true to enable experimental skia backend.
> > 
> > pdf_enable_xfa = false # Set false to remove XFA support (implies JS support).
> > pdf_enable_v8 = true  # Set false to remove Javascript support.
> > pdf_is_standalone = true  # Set for a non-embedded build.
> > is_component_build = false
> 
> Which target are you building? pdfium still passes for me.

Patchset 7 fails:
Error: 1> There is a syntax error in /usr/local/google/home/npm/pdfium/pdfium/DEPS
1> Line #68, character 35: "        Var("markupsafe_revision'),"

If you are trying to do this in Chromium, it probably won't work. You need to clone PDFium in a separate folder and gclient sync. Then just compile everything, PDFium is not very big.

Patch-set: 7
Reviewer: Nicolás Peña <6295@fca2d64a-0420-3532-b200-12848c95a47b>